substitutions:
  _TERRAFORM_VERSION: latest
  _OPA_VERSION: latest
steps:
- id: 'tf-init'
  name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['init', '-backend-config=bucket=${PROJECT_ID}_terraform']
  env:
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'
- id: 'tf-format'
  name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['fmt', '-list=true', '-write=false', '-diff=true', '-check=true', '.']
  waitFor: ['tf-init']
- id: 'tf-validate'
  name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['validate']
  waitFor: ['tf-init']
- id: 'tf-plan'
  name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  args: ['plan', '-lock=false', '-out=tfplan.binary']
  waitFor: ['tf-init']
- id: 'tf-convert-plan-to-json'
  name: 'gcr.io/${PROJECT_ID}/terraform:${_TERRAFORM_VERSION}'
  entrypoint: 'sh'
  args:
    - '-c'
    - |-
      terraform show -json tfplan.binary > tfplan.json
  waitFor: ['tf-plan']
- id: 'opa-eval'
  name: 'gcr.io/${PROJECT_ID}/openpolicyagent:${_OPA_VERSION}'
  args: ['eval', '--data', 'sample-bucket.rego', '--input', 'tfplan.json', 'data.terraform.validation.any_buckets_name_missing_team_label'] # docker run -v $PWD:/example openpolicyagent/opa eval --data example/sample-bucket.rego --input example/tfplan.json "data.terraform.validation.any_buckets_name_missing_team_label"
  waitFor: ['tf-init'] 
# artifacts:
#   objects:
#     location: 'gs://${PROJECT_ID}_cloudbuild/artifacts'
#     paths: ['tfplan.binary', 'tfplan.json']
